baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Learning Python with Dan"
description = "A guide on how to get started with Python for anyone!"
author = "Daniel Wertheimer"
theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"